<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            [
                'category_id' => 28, // Indoor Plants
                'brand_id' => 1,
                'name' => 'Snake Plant (Sansevieria Trifasciata)',
                'product_weight' => '2.5',
                'product_unit' => 'kg',
                'short_description' => 'A resilient, air-purifying indoor plant that is exceptionally easy to grow and maintain.',
                'description' => '<p>The Snake Plant is one of the most hardy indoor plants. It has stiff, sword-like leaves and can tolerate low light levels and infrequent watering, making it perfect for beginners.</p>',
                'purchase_price' => '250.00',
                'price' => '399.00',
                'offer_price' => '299.00',
                'tax' => '0.00',
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/snake_plant.jpg',
                'is_featured' => 1,
                'is_new' => 1,
                'is_best_seller' => 1,
                'status' => 1,
                'created_by' => 1,
                'plant_care' => '<ul><li>Water only when the soil is completely dry.</li><li>Thrives in indirect bright light but tolerates low light.</li></ul>',
                'additional_information' => '<ul><li>Excellent air purifier.</li><li>Slow-growing, low maintenance.</li></ul>',
            ],
            [
                'category_id' => 28, // Indoor Plants
                'brand_id' => 1,
                'name' => 'Aloe Vera Plant',
                'product_weight' => '1.5',
                'product_unit' => 'kg',
                'short_description' => 'A popular succulent known for its soothing gel and medicinal/healing properties.',
                'description' => '<p>Aloe Vera is a stemless or very short-stemmed plant. The leaves are thick and fleshy, green to grey-green, with some varieties showing flecks of white on their upper and lower stem surfaces.</p>',
                'purchase_price' => '150.00',
                'price' => '249.00',
                'offer_price' => '199.00',
                'tax' => '0.00',
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/aloe_vera.jpg',
                'is_featured' => 1,
                'is_new' => 1,
                'is_best_seller' => 0,
                'status' => 1,
                'created_by' => 1,
                'plant_care' => '<ul><li>Prefers bright, direct sunlight.</li><li>Water deeply but infrequently, allowing soil to dry out between waterings.</li></ul>',
                'additional_information' => '<ul><li>Gel is highly medicinal and soothing for burns.</li><li>Prefers well-draining succulent soil mix.</li></ul>',
            ],
            [
                'category_id' => 20, // Plants
                'brand_id' => 1,
                'name' => 'Areca Palm (Chrysalidocarpus Lutescens)',
                'product_weight' => '5.0',
                'product_unit' => 'kg',
                'short_description' => 'A gorgeous, feathery indoor palm that adds a tropical touch to any home or office.',
                'description' => '<p>Areca Palm is one of the most widely used palms for bright interiors. It features beautiful, arching fronds with multiple stems emerging from the base.</p>',
                'purchase_price' => '450.00',
                'price' => '699.00',
                'offer_price' => '549.00',
                'tax' => '0.00',
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/areca_palm.jpg',
                'is_featured' => 1,
                'is_new' => 0,
                'is_best_seller' => 1,
                'status' => 1,
                'created_by' => 1,
                'plant_care' => '<ul><li>Keep soil consistently moist but not soggy.</li><li>Thrives in filtered, bright indirect light.</li></ul>',
                'additional_information' => '<ul><li>Highly effective air purifier.</li><li>Improves indoor humidity levels.</li></ul>',
            ],
            [
                'category_id' => 28, // Indoor Plants
                'brand_id' => 1,
                'name' => 'Boston Fern (Nephrolepis Exaltata)',
                'product_weight' => '1.0',
                'product_unit' => 'kg',
                'short_description' => 'A classic indoor fern with lush, trailing fronds that look amazing in hanging baskets.',
                'description' => '<p>The Boston Fern is a highly popular houseplant known for its graceful, drooping fronds. It adds texture and vibrant green color to indoor spaces.</p>',
                'purchase_price' => '200.00',
                'price' => '349.00',
                'offer_price' => '279.00',
                'tax' => '0.00',
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/boston_fern.jpg',
                'is_featured' => 0,
                'is_new' => 1,
                'is_best_seller' => 0,
                'status' => 1,
                'created_by' => 1,
                'plant_care' => '<ul><li>Requires high humidity; mist regularly.</li><li>Keep soil evenly moist, never dry.</li></ul>',
                'additional_information' => '<ul><li>Safe for cats and dogs.</li><li>Thrives in medium to bright indirect light.</li></ul>',
            ],
            [
                'category_id' => 28, // Indoor Plants
                'brand_id' => 1,
                'name' => 'Spider Plant (Chlorophytum Comosum)',
                'product_weight' => '1.0',
                'product_unit' => 'kg',
                'short_description' => 'A delightful plant with long, arching green-and-white variegated leaves and baby "spiderettes".',
                'description' => '<p>Spider plants are extremely adaptable and easy-to-grow houseplants. They produce tiny white flowers and trailing plantlets that can be easily propagated.</p>',
                'purchase_price' => '180.00',
                'price' => '299.00',
                'offer_price' => '229.00',
                'tax' => '0.00',
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/spider_plant.jpg',
                'is_featured' => 0,
                'is_new' => 0,
                'is_best_seller' => 1,
                'status' => 1,
                'created_by' => 1,
                'plant_care' => '<ul><li>Water when the top inch of soil feels dry.</li><li>Provide bright, indirect sunlight.</li></ul>',
                'additional_information' => '<ul><li>Completely pet-friendly.</li><li>Very easy to propagate from baby offsets.</li></ul>',
            ],
            [
                'category_id' => 20, // Plants
                'brand_id' => 1,
                'name' => 'Jade Plant (Crassula Ovata)',
                'product_weight' => '0.8',
                'product_unit' => 'kg',
                'short_description' => 'A symbol of good luck and prosperity, this succulent features thick, shiny leaves.',
                'description' => '<p>The Jade Plant is a popular succulent houseplant with small, round, fleshy leaves. It grows like a miniature tree with a thick trunk and branching stems.</p>',
                'purchase_price' => '100.00',
                'price' => '199.00',
                'offer_price' => '149.00',
                'tax' => '0.00',
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/jade_plant.jpg',
                'is_featured' => 1,
                'is_new' => 1,
                'is_best_seller' => 1,
                'status' => 1,
                'created_by' => 1,
                'plant_care' => '<ul><li>Needs plenty of direct sun or bright light.</li><li>Water sparingly; let soil dry completely between waterings.</li></ul>',
                'additional_information' => '<ul><li>Often called the "Money Tree".</li><li>Can live for decades with proper care.</li></ul>',
            ],
            [
                'category_id' => 28, // Indoor Plants
                'brand_id' => 1,
                'name' => 'Monstera Deliciosa (Swiss Cheese Plant)',
                'product_weight' => '4.0',
                'product_unit' => 'kg',
                'short_description' => 'Famous for its iconic, naturally perforated leaves, adding instant dramatic jungle vibes.',
                'description' => '<p>Monstera Deliciosa is a stunning tropical climbing plant. As the plant matures, the large glossy green leaves develop deep splits and holes (fenestrations).</p>',
                'purchase_price' => '500.00',
                'price' => '899.00',
                'offer_price' => '749.00',
                'tax' => '0.00',
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/monstera.jpg',
                'is_featured' => 1,
                'is_new' => 0,
                'is_best_seller' => 1,
                'status' => 1,
                'created_by' => 1,
                'plant_care' => '<ul><li>Water when top 2 inches of soil are dry.</li><li>Provide support like a moss pole for climbing.</li></ul>',
                'additional_information' => '<ul><li>Prefers warm and humid conditions.</li><li>Clean leaves with a damp cloth to keep them shiny.</li></ul>',
            ],
            [
                'category_id' => 22, // Seeds
                'brand_id' => 1,
                'name' => 'Organic Cherry Tomato Seeds (Pack of 50)',
                'product_weight' => '0.02',
                'product_unit' => 'kg',
                'short_description' => 'High-germination organic seeds to grow sweet, juicy cherry tomatoes at home.',
                'description' => '<p>Grow your own fresh, organic cherry tomatoes in pots, balconies, or backyards. These seeds have a high germination rate and produce heavy yields of delicious fruit.</p>',
                'purchase_price' => '40.00',
                'price' => '99.00',
                'offer_price' => '79.00',
                'tax' => '0.00',
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/tomato_seeds.jpg',
                'is_featured' => 0,
                'is_new' => 1,
                'is_best_seller' => 0,
                'status' => 1,
                'created_by' => 1,
                'plant_care' => '<ul><li>Sow in well-draining starter soil.</li><li>Keep soil moist and place in full sunlight.</li></ul>',
                'additional_information' => '<ul><li>100% organic and non-GMO.</li><li>Matures in 60-70 days.</li></ul>',
            ],
            [
                'category_id' => 21, // Tools & Accessories
                'brand_id' => 1,
                'name' => 'Premium Potting Soil Mix (5kg)',
                'product_weight' => '5.0',
                'product_unit' => 'kg',
                'short_description' => 'Nutrient-rich, well-aerated potting mix for all indoor and outdoor plants.',
                'description' => '<p>This premium potting soil is enriched with organic compost, vermicompost, coco peat, and essential micro-nutrients to support healthy root development and lush foliage.</p>',
                'purchase_price' => '220.00',
                'price' => '499.00',
                'offer_price' => '399.00',
                'tax' => '0.00',
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/potting_soil.jpg',
                'is_featured' => 1,
                'is_new' => 0,
                'is_best_seller' => 1,
                'status' => 1,
                'created_by' => 1,
                'plant_care' => '<ul><li>Use directly for potting or mixing with garden soil.</li><li>No need to add external fertilizer for first 30 days.</li></ul>',
                'additional_information' => '<ul><li>Retains moisture while providing excellent drainage.</li><li>Lightweight and odor-free.</li></ul>',
            ],
            [
                'category_id' => 21, // Tools & Accessories
                'brand_id' => 1,
                'name' => 'Ergonomic Watering Can (5 Liters)',
                'product_weight' => '0.5',
                'product_unit' => 'kg',
                'short_description' => 'A lightweight watering can with a long spout and a fine spray rose for gentle watering.',
                'description' => '<p>This durable plastic watering can is designed for everyday gardening. The long spout allows you to reach deep foliage, while the sprinkler rose provides a gentle rain-like shower for seedlings.</p>',
                'purchase_price' => '300.00',
                'price' => '599.00',
                'offer_price' => '499.00',
                'tax' => '0.00',
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/watering_can.jpg',
                'is_featured' => 0,
                'is_new' => 1,
                'is_best_seller' => 1,
                'status' => 1,
                'created_by' => 1,
                'plant_care' => '<ul><li>Rinse with clean water after use.</li><li>Avoid keeping in direct hot sunlight for long periods.</li></ul>',
                'additional_information' => '<ul><li>Capacity: 5 Liters.</li><li>Sturdy double-handle design.</li></ul>',
            ],
            [
                'category_id' => 21, // Tools & Accessories
                'brand_id' => 1,
                'name' => 'Garden Trowel (Heavy Duty Steel)',
                'product_weight' => '0.3',
                'product_unit' => 'kg',
                'short_description' => 'Rust-resistant carbon steel garden trowel with a comfortable wooden handle.',
                'description' => '<p>Ideal for digging, transplanting, and loosening soil, this heavy-duty trowel features a strong steel blade that doesn\'t bend under pressure, paired with an ergonomic grip.</p>',
                'purchase_price' => '120.00',
                'price' => '299.00',
                'offer_price' => '249.00',
                'tax' => '0.00',
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/garden_trowel.jpg',
                'is_featured' => 0,
                'is_new' => 0,
                'is_best_seller' => 0,
                'status' => 1,
                'created_by' => 1,
                'plant_care' => '<ul><li>Wipe clean after use to prevent soil build-up.</li><li>Store in a dry place.</li></ul>',
                'additional_information' => '<ul><li>Rust-resistant coating.</li><li>Hanging loop on handle for easy storage.</li></ul>',
            ],
            [
                'category_id' => 27, // Pots By Material
                'brand_id' => 1,
                'name' => 'Terracotta Clay Pot (8 inches)',
                'product_weight' => '1.2',
                'product_unit' => 'kg',
                'short_description' => 'Classic breathable clay pot designed to keep soil aerated and roots healthy.',
                'description' => '<p>Terracotta pots are classic clay pots with a porous texture that allows air and moisture to penetrate the sides, preventing root rot and overwatering issues.</p>',
                'purchase_price' => '90.00',
                'price' => '199.00',
                'offer_price' => '159.00',
                'tax' => '0.00',
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/terracotta_pot.jpg',
                'is_featured' => 1,
                'is_new' => 1,
                'is_best_seller' => 0,
                'status' => 1,
                'created_by' => 1,
                'plant_care' => '<ul><li>Soak in water before first use.</li><li>Handle with care to avoid chipping.</li></ul>',
                'additional_information' => '<ul><li>Features a bottom drainage hole.</li><li>100% natural, eco-friendly clay.</li></ul>',
            ],
            [
                'category_id' => 27, // Pots By Material
                'brand_id' => 1,
                'name' => 'Ceramic Self-Watering Planter',
                'product_weight' => '1.8',
                'product_unit' => 'kg',
                'short_description' => 'Elegant glazed ceramic planter with a built-in water reservoir for easy plant care.',
                'description' => '<p>Ideal for busy plant parents, this self-watering ceramic planter keeps plants hydrated by drawing water from the bottom reservoir as needed, ensuring consistent moisture.</p>',
                'purchase_price' => '220.00',
                'price' => '449.00',
                'offer_price' => '349.00',
                'tax' => '0.00',
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/ceramic_planter.jpg',
                'is_featured' => 1,
                'is_new' => 0,
                'is_best_seller' => 1,
                'status' => 1,
                'created_by' => 1,
                'plant_care' => '<ul><li>Refill reservoir only when dry.</li><li>Clean the reservoir once a month to prevent build-up.</li></ul>',
                'additional_information' => '<ul><li>Includes water-level indicator.</li><li>Beautiful glazed finish.</li></ul>',
            ],
            [
                'category_id' => 21, // Tools & Accessories
                'brand_id' => 1,
                'name' => 'Organic Fertilizer Sticks (Pack of 30)',
                'product_weight' => '0.1',
                'product_unit' => 'kg',
                'short_description' => 'Slow-release food sticks providing continuous nourishment for up to 60 days.',
                'description' => '<p>These organic fertilizer spikes feed indoor and outdoor potted plants directly at the roots, promoting vibrant green leaves and abundant flowering without mess or runoff.</p>',
                'purchase_price' => '60.00',
                'price' => '149.00',
                'offer_price' => '119.00',
                'tax' => '0.00',
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/fertilizer_sticks.jpg',
                'is_featured' => 0,
                'is_new' => 0,
                'is_best_seller' => 0,
                'status' => 1,
                'created_by' => 1,
                'plant_care' => '<ul><li>Push spikes completely into moist soil around the plant edge.</li><li>Replace every 2 months.</li></ul>',
                'additional_information' => '<ul><li>NPK balanced formula.</li><li>Safe for pets and children when used as directed.</li></ul>',
            ],
            [
                'category_id' => 26, // Plants By Season
                'brand_id' => 1,
                'name' => 'English Lavender Plant',
                'product_weight' => '1.2',
                'product_unit' => 'kg',
                'short_description' => 'A gorgeous, fragrant herb with beautiful purple blooms and a relaxing aroma.',
                'description' => '<p>English Lavender is known for its sweet fragrance, beautiful purple flower spikes, and silver-green foliage. It grows well in pots and sunny gardens, attracting bees and butterflies.</p>',
                'purchase_price' => '220.00',
                'price' => '399.00',
                'offer_price' => '299.00',
                'tax' => '0.00',
                'stock_status' => 'in_stock',
                'thumbnail' => 'uploads/products/english_lavender.jpg',
                'is_featured' => 1,
                'is_new' => 1,
                'is_best_seller' => 1,
                'status' => 1,
                'created_by' => 1,
                'plant_care' => '<ul><li>Needs full, direct sunlight (at least 6 hours).</li><li>Allow soil to dry out significantly before watering again.</li></ul>',
                'additional_information' => '<ul><li>Leaves and flowers are highly aromatic.</li><li>Attracts pollinators.</li></ul>',
            ]
        ];

        foreach ($products as $productData) {
            // Slug is handled by Boot event or generateUniqueSlug, but let's also pass it or let it generate
            $product = new Product($productData);
            $product->slug = Str::slug($productData['name']);
            $product->save();
        }
    }
}

